const products = [
  {
    id: 1,
    name: "초당 옥수수(노랑이) 5입",
    description: "달달하고 아삭한 신선과일 옥수수",
    image: "/옥수수.png",
    price: 9990,
    originalPrice: 13900,
    discount: 28,
    origin: "국산",
    seller: "컬리",
    packaging: "냉장 (종이포장)",
    unit: "1팩",
    weight: "5입",
    notice:
      "초당옥수수 특성상 당도가 높아 각끝절편 표면에 점처럼 생길 수 있습니다. 해당 현상은 상품의 이상이 아닌 자연스러운 현상으로 안심하고 드셔도 좋습니다.",
  },
  {
    id: 2,
    name: "(특)신비 복숭아 700g",
    description: "아삭한 식감과 단맛 가득 복숭아",
    image: "/복숭아.jpg",
    price: 15900,
    originalPrice: 21900,
    discount: 27,
    origin: "국산",
    seller: "컬리",
    packaging: "냉장 (종이포장)",
    unit: "1팩",
    weight: "700g",
    notice:
      "복숭아는 수분이 많고 섬세한 과일이라 배송 중 일부 눌림이 있을 수 있습니다. 상품의 이상은 아니며 반품 사유가 되지 않습니다.",
  },
  {
    id: 3,
    name: "미국산 워싱턴 생체리 300g (1row)",
    description: "탱글탱글한 식감과 새콤달콤한 맛",
    image: "/채리.jpg",
    price: 8990,
    originalPrice: 12900,
    discount: 30,
    origin: "미국",
    seller: "컬리",
    packaging: "냉장 (종이포장)",
    unit: "1팩",
    weight: "300g",
    notice: "생체리는 수확 시기에 따라 크기나 색상이 다를 수 있습니다.",
  },
  {
    id: 4,
    name: "[노포기획] 웅강통식 돼지 양구이 1kg",
    description: "육즙 가득한 돼지 양념구이",
    image: "/돼지고기.jpg",
    price: 8990,
    originalPrice: 12900,
    discount: 30,
    origin: "국산",
    seller: "노포식품",
    packaging: "냉동 (비닐포장)",
    unit: "1팩",
    weight: "1kg",
    notice: "조리 시 기름이 튈 수 있으므로 주의가 필요합니다.",
  },
];

export default products;
